# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Integration to the carrier Danske Fragtmænd

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Metadata to use for the publishing to the SAR
Metadata:
  AWS::ServerlessRepo::Application:
    Name: thetis-ims-df-transport
    Description: Application for integrating Thetis IMS with the freight carrier Danske Fragtmænd.
    Author: thetis-apps
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['thetis-ims']
    HomePageUrl: https://github.com/thetis-apps/DFTransport
    SemanticVersion: 1.2.7
    SourceCodeUrl: https://github.com/thetis-apps/DFTransport
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs16.x

# Parameters of the application 
Parameters:
  ContextId:
    Type: String
    Description: Context that this application is handling events for.
    MinLength: '1'
  ClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientId
  ClientSecret:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientSecret
  ApiKey:
    Type: String
  DevOpsEmail:
    Description: The email address to send mail to when messages in the dead letter queue.
    Type: String
    MinLength: 4

Resources:  

  # Function that will run when a transport booking is created in Thetis IMS
  BookingHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Function that runs when a transport booking is created in Thetis IMS
      Handler: src/handlers/df-transport.bookingHandler
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
      Events:
        Request:
          Type: EventBridgeRule
          Properties:
            RetryPolicy:
              MaximumRetryAttempts: 0
            Pattern:
              source:
              - public.thetis-ims.com
              detail-type:
              - documentCreated
              detail:
                documentType:
                - TRANSPORT_BOOKING
                carrierName:
                - DF
                contextId:
                - Ref: ContextId
      MemorySize: 128
      Timeout: 100
      DeadLetterQueue:
        Type: SQS
        TargetArn:
          Fn::GetAtt:
          - DeadLetterQueue
          - Arn
          
  # Initialisation of DF integration in context        
  InitResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - InitializeFunction
        - Arn
      Version: 6
  InitializeFunction:
    Type: AWS::Serverless::Function
    DeletionPolicy: Delete
    Properties:
      Handler: src/handlers/df-transport.initializer
      MemorySize: 2048
      Timeout: 30
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
    

  # Our standard monitoring setup      
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties: 
      KmsMasterKeyId: alias/aws/sqs
